### ISSUE TITLE
Directions to Event

### ISSUE THREAD

**Issue by ernie1994** [medricr/group-project#6]
##User Story
As a user, I want to know how far away I am from nearby events so that I can choose to go to an event.

##Acceptance Criteria
- [x] Retrieve current location data
- [x] Retrieve location data from a particular event
- [x] Use a Map/Navigation API to calculate the drive time between the two locations
- [x] Create a button that shows driving directions from the start location to the event location

**Comment by YaroslavPetsenyuk** [comment]
We implemented markers population each time an event or hotel is selected
